[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_N8N_WEBHOOK_URL = "https://n8n-latest-detj.onrender.com/webhook/generate-invoice"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 